export const AllBills = [
  {
    id : 1,
    no : '1',
    approve : 'อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'โน๊ตบุ๊ค',
    catgoeries : 'อุปกรณ์คอมพิวเตอร์',
    type : 'คอมพิวเตอร์',
    amount : '10',
    price : '100',
    total : '10,000',
    exprice_date : null,
    img : ''
  },
  {
    id : 2,
    no : '2',
    approve : 'อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'หน้าจอ',
    catgoeries : 'วัสดุและอุปกรณ์',
    type : 'คอมพิวเตอร์',
    amount : '3',
    price : '2,000',
    total : '6,000',
    exprice_date : null,
    img : ''
  },
  {
    id : 3,
    no : '3',
    approve : 'อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'โคเมน',
    catgoeries : 'ซิมการ์ด',
    type : 'คอมพิวเตอร์',
    amount : '10',
    price : '100',
    total : '10,000',
    exprice_date : null,
    img : ''
  },
  {
    id : 4,
    no : '4',
    approve : 'อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'โน๊ตบุ๊ค',
    catgoeries : 'อุปกรณ์คอมพิวเตอร์',
    type : 'คอมพิวเตอร์',
    amount : '3',
    price : '2,000',
    total : '6,000',
    exprice_date : null,
    img : ''
  },
  {
    id : 5,
    no : '5',
    approve : 'อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'โน๊ตบุ๊ค',
    catgoeries : 'วัสดุและอุปกรณ์',
    type : 'คอมพิวเตอร์',
    amount : '10',
    price : '100',
    total : '10,000',
    exprice_date : null,
    img : ''
  },
  {
    id : 6,
    no : '6',
    approve : 'ไม่อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'โน๊ตบุ๊ค',
    catgoeries : 'อุปกรณ์คอมพิวเตอร์',
    type : 'คอมพิวเตอร์',
    amount : '10',
    price : '100',
    total : '10,000',
    exprice_date : null,
    img : ''
  },
  {
    id : 7,
    no : '7',
    approve : 'อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'โน๊ตบุ๊ค',
    catgoeries : 'วัสดุและอุปกรณ์',
    type : 'คอมพิวเตอร์',
    amount : '3',
    price : '2,000',
    total : '6,000',
    exprice_date : null,
    img : ''
  },
  {
    id : 8,
    no : '8',
    approve : 'อนุมัติ',
    bills_no : 'B01202012090000',
    list_name : 'โน๊ตบุ๊ค',
    catgoeries : 'อุปกรณ์คอมพิวเตอร์',
    type : 'คอมพิวเตอร์',
    amount : '10',
    price : '100',
    total : '10,000',
    exprice_date : null,
    img : ''
  },

];
